# game_data.py

# === Drop Table ===
drop_table = [
    {"name": "Rusty Dagger", "type": "weapon", "effect": "+1 damage", "value": 5, "weight": 10},
    {"name": "Healing Herb", "type": "potion", "effect": "+5 HP", "value": 10, "weight": 10},
    {"name": "Mana Leaf", "type": "potion", "effect": "+5 MP", "value": 12, "weight": 9},
    {"name": "Old Leather Armor", "type": "armor", "effect": "+1 defense", "value": 15, "weight": 9},
    {"name": "Steel Sword", "type": "weapon", "effect": "+3 damage", "value": 30, "weight": 7},
    {"name": "Minor Rune Stone", "type": "magic", "effect": "+2 mana", "value": 20, "weight": 7},
    {"name": "Golden Elixir", "type": "potion", "effect": "Restore all HP", "value": 100, "weight": 3},
    {"name": "Phantom Cloak", "type": "armor", "effect": "+2 dodge", "value": 50, "weight": 2},
    {"name": "Demon Core", "type": "relic", "effect": "+5 all stats", "value": 250, "weight": 1},
    {"name": "Iron Axe", "type": "weapon", "effect": "+2 damage", "value": 20, "weight": 8},
    {"name": "Chainmail Vest", "type": "armor", "effect": "+2 defense", "value": 25, "weight": 7},
    {"name": "Elven Pendant", "type": "magic", "effect": "+3 mana", "value": 35, "weight": 6},
    {"name": "Hero’s Brew", "type": "potion", "effect": "Restore all HP", "value": 120, "weight": 3},
    {"name": "Arcane Band", "type": "magic", "effect": "+1 mana", "value": 12, "weight": 9},
    {"name": "Stone Armor", "type": "armor", "effect": "+3 defense", "value": 40, "weight": 6},
    {"name": "Silver Blade", "type": "weapon", "effect": "+4 damage", "value": 45, "weight": 5},
    {"name": "Vitality Root", "type": "potion", "effect": "+10 HP", "value": 25, "weight": 7},
    {"name": "Mana Crystal", "type": "potion", "effect": "+10 MP", "value": 28, "weight": 7},
    {"name": "Warding Cloak", "type": "armor", "effect": "+2 defense", "value": 22, "weight": 6},
    {"name": "Ancient Grimoire", "type": "magic", "effect": "+5 mana", "value": 60, "weight": 4},
    {"name": "Bloodfang Dagger", "type": "weapon", "effect": "+5 damage", "value": 70, "weight": 3},
    {"name": "Guardian Plate", "type": "armor", "effect": "+4 defense", "value": 65, "weight": 3},
    {"name": "Talisman of Power", "type": "relic", "effect": "+3 all stats", "value": 100, "weight": 2},
    {"name": "Radiant Flask", "type": "potion", "effect": "Restore all HP", "value": 90, "weight": 3},
    {"name": "Etheric Band", "type": "magic", "effect": "+4 mana", "value": 50, "weight": 5},
    {"name": "Crimson Elixir", "type": "potion", "effect": "+20 HP", "value": 40, "weight": 4},
    {"name": "Cobalt Elixir", "type": "potion", "effect": "+20 MP", "value": 42, "weight": 4},
    {"name": "Knight’s Blade", "type": "weapon", "effect": "+6 damage", "value": 85, "weight": 2},
    {"name": "Runed Vest", "type": "armor", "effect": "+3 defense", "value": 48, "weight": 4},
    {"name": "Soul Pendant", "type": "magic", "effect": "+6 mana", "value": 70, "weight": 2},
    {"name": "Void Amulet", "type": "relic", "effect": "+4 all stats", "value": 200, "weight": 2},
    {"name": "Ashen Ring", "type": "magic", "effect": "+2 mana", "value": 18, "weight": 8},
    {"name": "Shadowsteel Sword", "type": "weapon", "effect": "+7 damage", "value": 100, "weight": 2},
    {"name": "Dragon Hide", "type": "armor", "effect": "+5 defense", "value": 90, "weight": 2},
    {"name": "Blessed Tonic", "type": "potion", "effect": "+30 HP", "value": 60, "weight": 2},
    {"name": "Sapphire Flask", "type": "potion", "effect": "+30 MP", "value": 62, "weight": 2},
    {"name": "Mystic Robe", "type": "armor", "effect": "+1 defense", "value": 18, "weight": 8},
    {"name": "Shadow Cloak", "type": "armor", "effect": "+2 dodge", "value": 55, "weight": 3},
    {"name": "Champion’s Edge", "type": "weapon", "effect": "+8 damage", "value": 115, "weight": 1},
    {"name": "Overseer Mask", "type": "relic", "effect": "+6 all stats", "value": 300, "weight": 1},
    {"name": "Witchbrew", "type": "potion", "effect": "+15 HP", "value": 35, "weight": 6},
    {"name": "Elder Flask", "type": "potion", "effect": "+15 MP", "value": 36, "weight": 6},
    {"name": "Bone Club", "type": "weapon", "effect": "+2 damage", "value": 18, "weight": 8},
    {"name": "Leather Tunic", "type": "armor", "effect": "+1 defense", "value": 10, "weight": 9},
    {"name": "Silver Locket", "type": "magic", "effect": "+3 mana", "value": 32, "weight": 6},
    {"name": "Vial of Life", "type": "potion", "effect": "Restore all HP", "value": 110, "weight": 3},
    {"name": "Infernal Flask", "type": "potion", "effect": "+50 HP", "value": 80, "weight": 1},
    {"name": "Arc Flask", "type": "potion", "effect": "+50 MP", "value": 82, "weight": 1},
    {"name": "Titan Plate", "type": "armor", "effect": "+6 defense", "value": 100, "weight": 1},
    {"name": "Dagger of Swiftness", "type": "weapon", "effect": "+3 damage", "value": 25, "weight": 6},
    {"name": "Forest Blade", "type": "weapon", "effect": "+4 damage", "value": 38, "weight": 4},
    {"name": "Bandit Vest", "type": "armor", "effect": "+2 defense", "value": 26, "weight": 6},
    {"name": "Amulet of Clarity", "type": "magic", "effect": "+3 mana", "value": 28, "weight": 5},
    {"name": "Glowing Ring", "type": "magic", "effect": "+1 mana", "value": 10, "weight": 9},
    {"name": "Chaos Relic", "type": "relic", "effect": "+2 all stats", "value": 80, "weight": 3},
    {"name": "Stamina Flask", "type": "potion", "effect": "+25 HP", "value": 45, "weight": 3},
    {"name": "Focus Flask", "type": "potion", "effect": "+25 MP", "value": 47, "weight": 3},
    {"name": "Dragon Fang", "type": "weapon", "effect": "+9 damage", "value": 130, "weight": 1},
    {"name": "Mirror Shield", "type": "armor", "effect": "+7 defense", "value": 110, "weight": 1},
    {"name": "Heart of the Ancients", "type": "relic", "effect": "+7 all stats", "value": 350, "weight": 1},
]

# === Skill Table ===
skill_table = [
    {"name": "Ember Spark", "damage": "1d4", "attacks": 1, "healing": 0, "mana_cost": 2, "weight": 10},
    {"name": "Piercing Shot", "damage": "1d6", "attacks": 1, "healing": 0, "mana_cost": 3, "weight": 10},
    {"name": "Quick Slash", "damage": "1d4", "attacks": 2, "healing": 0, "mana_cost": 4, "weight": 9},
    {"name": "Healing Pulse", "damage": "0", "attacks": 0, "healing": 2, "mana_cost": 4, "weight": 8},
    {"name": "Frost Needle", "damage": "1d8", "attacks": 1, "healing": 0, "mana_cost": 6, "weight": 8},
    {"name": "Shadow Jab", "damage": "1d6", "attacks": 2, "healing": 0, "mana_cost": 6, "weight": 7},
    {"name": "Radiant Surge", "damage": "1d4", "attacks": 1, "healing": 1, "mana_cost": 5, "weight": 7},
    {"name": "Arcane Burst", "damage": "2d6", "attacks": 1, "healing": 0, "mana_cost": 8, "weight": 6},
    {"name": "Whirlwind", "damage": "1d4", "attacks": 3, "healing": 0, "mana_cost": 7, "weight": 6},
    {"name": "Dark Recovery", "damage": "1d4", "attacks": 1, "healing": 2, "mana_cost": 6, "weight": 5},
    {"name": "Thunderclap", "damage": "1d10", "attacks": 1, "healing": 0, "mana_cost": 9, "weight": 5},
    {"name": "Divine Light", "damage": "0", "attacks": 0, "healing": 4, "mana_cost": 5, "weight": 6},
    {"name": "Bone Strike", "damage": "2d4", "attacks": 1, "healing": 0, "mana_cost": 6, "weight": 6},
    {"name": "Venom Fang", "damage": "1d6", "attacks": 2, "healing": 0, "mana_cost": 7, "weight": 6},
    {"name": "Ice Lance", "damage": "1d10", "attacks": 1, "healing": 0, "mana_cost": 9, "weight": 5},
    {"name": "Blinding Flash", "damage": "1d4", "attacks": 1, "healing": 1, "mana_cost": 5, "weight": 6},
    {"name": "Firestorm", "damage": "1d6", "attacks": 4, "healing": 0, "mana_cost": 10, "weight": 4},
    {"name": "Echo Wave", "damage": "1d8", "attacks": 2, "healing": 0, "mana_cost": 8, "weight": 5},
    {"name": "Spirit Mend", "damage": "0", "attacks": 0, "healing": 6, "mana_cost": 6, "weight": 4},
    {"name": "Meteor Bolt", "damage": "3d6", "attacks": 1, "healing": 0, "mana_cost": 12, "weight": 3},
    {"name": "Twilight Slash", "damage": "2d8", "attacks": 1, "healing": 0, "mana_cost": 11, "weight": 3},
    {"name": "Scorching Ray", "damage": "1d6", "attacks": 3, "healing": 0, "mana_cost": 9, "weight": 4},
    {"name": "Mind Pierce", "damage": "1d10", "attacks": 1, "healing": 1, "mana_cost": 9, "weight": 4},
    {"name": "Soul Drain", "damage": "1d6", "attacks": 2, "healing": 2, "mana_cost": 10, "weight": 3},
    {"name": "Radiant Blast", "damage": "2d6", "attacks": 1, "healing": 2, "mana_cost": 11, "weight": 3},
    {"name": "Flame Slash", "damage": "2d4", "attacks": 2, "healing": 0, "mana_cost": 7, "weight": 5},
    {"name": "Ice Shard", "damage": "1d8", "attacks": 2, "healing": 0, "mana_cost": 9, "weight": 4},
    {"name": "Dark Flame", "damage": "1d12", "attacks": 1, "healing": 0, "mana_cost": 10, "weight": 4},
    {"name": "Solar Burst", "damage": "3d4", "attacks": 1, "healing": 1, "mana_cost": 11, "weight": 3},
    {"name": "Lunar Touch", "damage": "0", "attacks": 0, "healing": 8, "mana_cost": 7, "weight": 3},
    {"name": "Thunderstorm", "damage": "2d6", "attacks": 2, "healing": 0, "mana_cost": 12, "weight": 2},
    {"name": "Raging Tempest", "damage": "1d8", "attacks": 4, "healing": 0, "mana_cost": 13, "weight": 2},
    {"name": "Void Touch", "damage": "2d4", "attacks": 1, "healing": 3, "mana_cost": 9, "weight": 3},
    {"name": "Hellfire Blast", "damage": "3d8", "attacks": 1, "healing": 0, "mana_cost": 14, "weight": 1},
    {"name": "Blood Boil", "damage": "1d6", "attacks": 3, "healing": 1, "mana_cost": 11, "weight": 2},
    {"name": "Crystal Edge", "damage": "2d6", "attacks": 2, "healing": 0, "mana_cost": 12, "weight": 2},
    {"name": "Echo Slam", "damage": "1d10", "attacks": 2, "healing": 0, "mana_cost": 11, "weight": 3},
    {"name": "Phantom Slice", "damage": "1d8", "attacks": 3, "healing": 0, "mana_cost": 12, "weight": 2},
    {"name": "Glacial Crush", "damage": "2d10", "attacks": 1, "healing": 0, "mana_cost": 14, "weight": 1},
    {"name": "Nature's Touch", "damage": "0", "attacks": 0, "healing": 5, "mana_cost": 4, "weight": 5},
    {"name": "Shadow Bite", "damage": "2d4", "attacks": 2, "healing": 0, "mana_cost": 8, "weight": 5},
    {"name": "Severing Light", "damage": "2d6", "attacks": 1, "healing": 0, "mana_cost": 10, "weight": 4},
    {"name": "Boulder Toss", "damage": "2d8", "attacks": 1, "healing": 0, "mana_cost": 12, "weight": 3},
    {"name": "Flame Wheel", "damage": "1d6", "attacks": 4, "healing": 0, "mana_cost": 11, "weight": 3},
    {"name": "Light of Hope", "damage": "0", "attacks": 0, "healing": 10, "mana_cost": 9, "weight": 2},
    {"name": "Crushing Blow", "damage": "3d6", "attacks": 1, "healing": 0, "mana_cost": 13, "weight": 2},
    {"name": "Toxic Spit", "damage": "1d8", "attacks": 2, "healing": 0, "mana_cost": 10, "weight": 3},
    {"name": "Ashen Grasp", "damage": "2d4", "attacks": 2, "healing": 0, "mana_cost": 9, "weight": 3},
    {"name": "Sacred Flame", "damage": "2d6", "attacks": 1, "healing": 2, "mana_cost": 11, "weight": 3},
    {"name": "Windslice", "damage": "1d4", "attacks": 5, "healing": 0, "mana_cost": 12, "weight": 2},
    {"name": "Stone Blast", "damage": "2d10", "attacks": 1, "healing": 0, "mana_cost": 15, "weight": 1},
    {"name": "Burning Lance", "damage": "2d8", "attacks": 1, "healing": 0, "mana_cost": 12, "weight": 2},
    {"name": "Ghoul Touch", "damage": "1d6", "attacks": 2, "healing": 3, "mana_cost": 11, "weight": 2},
    {"name": "Doom Ray", "damage": "4d6", "attacks": 1, "healing": 0, "mana_cost": 16, "weight": 1},
    {"name": "Starbolt", "damage": "3d4", "attacks": 2, "healing": 0, "mana_cost": 14, "weight": 2},
    {"name": "Aurora Veil", "damage": "0", "attacks": 0, "healing": 12, "mana_cost": 10, "weight": 1},
    {"name": "Arc Lightning", "damage": "1d6", "attacks": 5, "healing": 0, "mana_cost": 13, "weight": 1},
    {"name": "Final Judgment", "damage": "5d6", "attacks": 1, "healing": 0, "mana_cost": 18, "weight": 1},
    {"name": "Dragon’s Breath", "damage": "3d8", "attacks": 1, "healing": 0, "mana_cost": 17, "weight": 1},
    {"name": "Echoing Vow", "damage": "1d4", "attacks": 6, "healing": 0, "mana_cost": 13, "weight": 1},
    {"name": "Spectral Grasp", "damage": "1d8", "attacks": 2, "healing": 2, "mana_cost": 12, "weight": 1},
    {"name": "Phoenix Flame", "damage": "3d6", "attacks": 1, "healing": 4, "mana_cost": 16, "weight": 1},
    {"name": "Rune Implosion", "damage": "4d4", "attacks": 2, "healing": 0, "mana_cost": 15, "weight": 1},
    {"name": "Oblivion Ray", "damage": "6d6", "attacks": 1, "healing": 0, "mana_cost": 20, "weight": 1},
]

# === Monster List ===
monster_list = [
    {"name": "Slime", "health": 6, "damage": 1},
    {"name": "Goblin", "health": 8, "damage": 2},
    {"name": "Wolf", "health": 12, "damage": 3},
    {"name": "Slime 2", "health": 16, "damage": 4},
    {"name": "Goblin 2", "health": 20, "damage": 5},
    {"name": "Wolf 2", "health": 25, "damage": 6},
    {"name": "Bat", "health": 7, "damage": 2},
    {"name": "Zombie", "health": 15, "damage": 3},
    {"name": "Skeleton", "health": 18, "damage": 4},
    {"name": "Bandit", "health": 22, "damage": 5},
    {"name": "Ooze", "health": 10, "damage": 3},
    {"name": "Imp", "health": 13, "damage": 3},
    {"name": "Dire Rat", "health": 14, "damage": 4},
    {"name": "Wasp", "health": 9, "damage": 3},
    {"name": "Venom Slime", "health": 18, "damage": 5},
    {"name": "Forest Spider", "health": 16, "damage": 4},
    {"name": "Lurking Shade", "health": 20, "damage": 6},
    {"name": "Thornbeast", "health": 24, "damage": 7},
    {"name": "Cave Crab", "health": 28, "damage": 7},
    {"name": "Blazing Lizard", "health": 30, "damage": 8},
    {"name": "Fire Bat", "health": 25, "damage": 6},
    {"name": "Ash Golem", "health": 35, "damage": 9},
    {"name": "Feral Cat", "health": 17, "damage": 5},
    {"name": "Bandit Archer", "health": 22, "damage": 6},
    {"name": "Bog Wight", "health": 26, "damage": 7},
    {"name": "Swamp Leech", "health": 21, "damage": 6},
    {"name": "Ghostling", "health": 19, "damage": 5},
    {"name": "Wraith", "health": 28, "damage": 8},
    {"name": "Ghoul", "health": 32, "damage": 9},
    {"name": "Frost Spider", "health": 30, "damage": 8},
    {"name": "Snow Wolf", "health": 35, "damage": 9},
    {"name": "Ice Elemental", "health": 40, "damage": 10},
    {"name": "Yeti Cub", "health": 38, "damage": 10},
    {"name": "Ice Bat", "health": 28, "damage": 7},
    {"name": "Rogue Mage", "health": 30, "damage": 11},
    {"name": "Stone Golem", "health": 45, "damage": 12},
    {"name": "Enchanted Armor", "health": 50, "damage": 13},
    {"name": "Cursed Knight", "health": 55, "damage": 14},
    {"name": "Dark Wolf", "health": 52, "damage": 13},
    {"name": "Bone Serpent", "health": 60, "damage": 15},
    {"name": "Fungal Beast", "health": 48, "damage": 12},
    {"name": "Scorpion", "health": 33, "damage": 9},
    {"name": "Flesh Golem", "health": 65, "damage": 16},
    {"name": "Thunder Lizard", "health": 70, "damage": 17},
    {"name": "Storm Bat", "health": 42, "damage": 11},
    {"name": "Lightning Elemental", "health": 75, "damage": 18},
    {"name": "Shadow Wyrm", "health": 80, "damage": 19},
    {"name": "Vampire Thrall", "health": 68, "damage": 17},
    {"name": "Specter", "health": 66, "damage": 16},
    {"name": "Crystal Spider", "health": 72, "damage": 17},
    {"name": "Iron Bear", "health": 85, "damage": 20},
    {"name": "Cave Troll", "health": 90, "damage": 21},
    {"name": "Bone Golem", "health": 95, "damage": 22},
    {"name": "Inferno Slime", "health": 88, "damage": 21},
    {"name": "Blood Hound", "health": 76, "damage": 19},
    {"name": "Hellbat", "health": 70, "damage": 18},
    {"name": "Nightmare", "health": 100, "damage": 23},
    {"name": "Dark Revenant", "health": 110, "damage": 24},
    {"name": "Arcane Construct", "health": 120, "damage": 25},
    {"name": "Twilight Stalker", "health": 130, "damage": 26},
    {"name": "Cursed Shade", "health": 140, "damage": 27},
    {"name": "Plague Rat", "health": 62, "damage": 14},
    {"name": "Toxic Crawler", "health": 78, "damage": 17},
    {"name": "Molten Fiend", "health": 150, "damage": 28},
    {"name": "Elder Wolf", "health": 95, "damage": 22},
    {"name": "Ancient Slime", "health": 98, "damage": 22},
    {"name": "Silver Knight", "health": 125, "damage": 26},
    {"name": "Giant Bat", "health": 90, "damage": 21},
    {"name": "Spectral Warrior", "health": 135, "damage": 27},
    {"name": "Lava Hound", "health": 145, "damage": 28},
    {"name": "Obsidian Golem", "health": 160, "damage": 30},
    {"name": "Corrupted Mage", "health": 155, "damage": 29},
    {"name": "Void Spawn", "health": 170, "damage": 32},
    {"name": "Ancient Shade", "health": 180, "damage": 33},
    {"name": "Phantom Beast", "health": 190, "damage": 34},
    {"name": "Dragon Whelp", "health": 200, "damage": 35}
]
