# game_data.py

# === Drop Table ===
drop_table = [
    {"name": "Rusty Dagger", "type": "weapon", "bonus": {"damage": 1}, "value": 5, "weight": 10},
    {"name": "Healing Herb", "type": "potion", "bonus": {"max_health": 5}, "value": 10, "weight": 10},
    {"name": "Mana Leaf", "type": "potion", "bonus": {"max_mana": 5}, "value": 12, "weight": 9},
    {"name": "Steel Sword", "type": "weapon", "bonus": {"damage": 3}, "value": 30, "weight": 7},
    {"name": "Minor Rune Stone", "type": "magic", "bonus": {"max_mana": 2}, "value": 20, "weight": 7},
    {"name": "Golden Elixir", "type": "potion", "restore_full": True, "value": 100, "weight": 3},
    {"name": "Demon Core", "type": "relic", "bonus": {"damage": 5, "max_health": 5, "max_mana": 5}, "value": 250, "weight": 1},
    {"name": "Iron Axe", "type": "weapon", "bonus": {"damage": 2}, "value": 20, "weight": 8},
    {"name": "Elven Pendant", "type": "magic", "bonus": {"max_mana": 3}, "value": 35, "weight": 6},
    {"name": "Hero’s Brew", "type": "potion", "restore_full": True, "value": 120, "weight": 3},
    {"name": "Arcane Band", "type": "magic", "bonus": {"max_mana": 1}, "value": 12, "weight": 9},
    {"name": "Silver Blade", "type": "weapon", "bonus": {"damage": 4}, "value": 45, "weight": 5},
    {"name": "Vitality Root", "type": "potion", "bonus": {"max_health": 10}, "value": 25, "weight": 7},
    {"name": "Mana Crystal", "type": "potion", "bonus": {"max_mana": 10}, "value": 28, "weight": 7},
    {"name": "Ancient Grimoire", "type": "magic", "bonus": {"max_mana": 5}, "value": 60, "weight": 4},
    {"name": "Bloodfang Dagger", "type": "weapon", "bonus": {"damage": 5}, "value": 70, "weight": 3},
    {"name": "Talisman of Power", "type": "relic", "bonus": {"damage": 3, "max_health": 3, "max_mana": 3}, "value": 100, "weight": 2},
    {"name": "Radiant Flask", "type": "potion", "restore_full": True, "value": 90, "weight": 3},
    {"name": "Etheric Band", "type": "magic", "bonus": {"max_mana": 4}, "value": 50, "weight": 5},
    {"name": "Crimson Elixir", "type": "potion", "bonus": {"max_health": 20}, "value": 40, "weight": 4},
    {"name": "Cobalt Elixir", "type": "potion", "bonus": {"max_mana": 20}, "value": 42, "weight": 4},
    {"name": "Knight’s Blade", "type": "weapon", "bonus": {"damage": 6}, "value": 85, "weight": 2},
    {"name": "Soul Pendant", "type": "magic", "bonus": {"max_mana": 6}, "value": 70, "weight": 2},
    {"name": "Void Amulet", "type": "relic", "bonus": {"damage": 4, "max_health": 4, "max_mana": 4}, "value": 200, "weight": 2},
    {"name": "Ashen Ring", "type": "magic", "bonus": {"max_mana": 2}, "value": 18, "weight": 8},
    {"name": "Shadowsteel Sword", "type": "weapon", "bonus": {"damage": 7}, "value": 100, "weight": 2},
    {"name": "Blessed Tonic", "type": "potion", "bonus": {"max_health": 30}, "value": 60, "weight": 2},
    {"name": "Sapphire Flask", "type": "potion", "bonus": {"max_mana": 30}, "value": 62, "weight": 2},
    {"name": "Champion’s Edge", "type": "weapon", "bonus": {"damage": 8}, "value": 115, "weight": 1},
    {"name": "Overseer Mask", "type": "relic", "bonus": {"damage": 6, "max_health": 6, "max_mana": 6}, "value": 300, "weight": 1},
    {"name": "Witchbrew", "type": "potion", "bonus": {"max_health": 15}, "value": 35, "weight": 6},
    {"name": "Elder Flask", "type": "potion", "bonus": {"max_mana": 15}, "value": 36, "weight": 6},
    {"name": "Bone Club", "type": "weapon", "bonus": {"damage": 2}, "value": 18, "weight": 8},
    {"name": "Silver Locket", "type": "magic", "bonus": {"max_mana": 3}, "value": 32, "weight": 6},
    {"name": "Vial of Life", "type": "potion", "restore_full": True, "value": 110, "weight": 3},
    {"name": "Infernal Flask", "type": "potion", "bonus": {"max_health": 50}, "value": 80, "weight": 1},
    {"name": "Arc Flask", "type": "potion", "bonus": {"max_mana": 50}, "value": 82, "weight": 1},
    {"name": "Dagger of Swiftness", "type": "weapon", "bonus": {"damage": 3}, "value": 25, "weight": 6},
    {"name": "Forest Blade", "type": "weapon", "bonus": {"damage": 4}, "value": 38, "weight": 4},
    {"name": "Amulet of Clarity", "type": "magic", "bonus": {"max_mana": 3}, "value": 28, "weight": 5},
    {"name": "Glowing Ring", "type": "magic", "bonus": {"max_mana": 1}, "value": 10, "weight": 9},
    {"name": "Chaos Relic", "type": "relic", "bonus": {"damage": 2, "max_health": 2, "max_mana": 2}, "value": 80, "weight": 3},
    {"name": "Stamina Flask", "type": "potion", "bonus": {"max_health": 25}, "value": 45, "weight": 3},
    {"name": "Focus Flask", "type": "potion", "bonus": {"max_mana": 25}, "value": 47, "weight": 3},
    {"name": "Dragon Fang", "type": "weapon", "bonus": {"damage": 9}, "value": 130, "weight": 1},
    {"name": "Heart of the Ancients", "type": "relic", "bonus": {"damage": 7, "max_health": 7, "max_mana": 7}, "value": 350, "weight": 1},
]

# === Skill Table ===
skill_table = [
    {"name": "Ember Spark", "damage": "1d4", "attacks": 1, "healing": 0, "mana_cost": 2, "weight": 10},
    {"name": "Piercing Shot", "damage": "1d6", "attacks": 1, "healing": 0, "mana_cost": 3, "weight": 10},
    {"name": "Quick Slash", "damage": "1d4", "attacks": 2, "healing": 0, "mana_cost": 4, "weight": 9},
    {"name": "Healing Pulse", "damage": "0", "attacks": 0, "healing": 2, "mana_cost": 4, "weight": 8},
    {"name": "Frost Needle", "damage": "1d8", "attacks": 1, "healing": 0, "mana_cost": 6, "weight": 8},
    {"name": "Shadow Jab", "damage": "1d6", "attacks": 2, "healing": 0, "mana_cost": 6, "weight": 7},
    {"name": "Radiant Surge", "damage": "1d4", "attacks": 1, "healing": 1, "mana_cost": 5, "weight": 7},
    {"name": "Arcane Burst", "damage": "2d6", "attacks": 1, "healing": 0, "mana_cost": 8, "weight": 6},
    {"name": "Whirlwind", "damage": "1d4", "attacks": 3, "healing": 0, "mana_cost": 7, "weight": 6},
    {"name": "Dark Recovery", "damage": "1d4", "attacks": 1, "healing": 2, "mana_cost": 6, "weight": 5},
    {"name": "Thunderclap", "damage": "1d10", "attacks": 1, "healing": 0, "mana_cost": 9, "weight": 5},
    {"name": "Divine Light", "damage": "0", "attacks": 0, "healing": 4, "mana_cost": 5, "weight": 6},
    {"name": "Bone Strike", "damage": "2d4", "attacks": 1, "healing": 0, "mana_cost": 6, "weight": 6},
    {"name": "Venom Fang", "damage": "1d6", "attacks": 2, "healing": 0, "mana_cost": 7, "weight": 6},
    {"name": "Ice Lance", "damage": "1d10", "attacks": 1, "healing": 0, "mana_cost": 9, "weight": 5},
    {"name": "Blinding Flash", "damage": "1d4", "attacks": 1, "healing": 1, "mana_cost": 5, "weight": 6},
    {"name": "Firestorm", "damage": "1d6", "attacks": 4, "healing": 0, "mana_cost": 10, "weight": 4},
    {"name": "Echo Wave", "damage": "1d8", "attacks": 2, "healing": 0, "mana_cost": 8, "weight": 5},
    {"name": "Spirit Mend", "damage": "0", "attacks": 0, "healing": 6, "mana_cost": 6, "weight": 4},
    {"name": "Meteor Bolt", "damage": "3d6", "attacks": 1, "healing": 0, "mana_cost": 12, "weight": 3},
    {"name": "Twilight Slash", "damage": "2d8", "attacks": 1, "healing": 0, "mana_cost": 11, "weight": 3},
    {"name": "Scorching Ray", "damage": "1d6", "attacks": 3, "healing": 0, "mana_cost": 9, "weight": 4},
    {"name": "Mind Pierce", "damage": "1d10", "attacks": 1, "healing": 1, "mana_cost": 9, "weight": 4},
    {"name": "Soul Drain", "damage": "1d6", "attacks": 2, "healing": 2, "mana_cost": 10, "weight": 3},
    {"name": "Radiant Blast", "damage": "2d6", "attacks": 1, "healing": 2, "mana_cost": 11, "weight": 3},
    {"name": "Flame Slash", "damage": "2d4", "attacks": 2, "healing": 0, "mana_cost": 7, "weight": 5},
    {"name": "Ice Shard", "damage": "1d8", "attacks": 2, "healing": 0, "mana_cost": 9, "weight": 4},
    {"name": "Dark Flame", "damage": "1d12", "attacks": 1, "healing": 0, "mana_cost": 10, "weight": 4},
    {"name": "Solar Burst", "damage": "3d4", "attacks": 1, "healing": 1, "mana_cost": 11, "weight": 3},
    {"name": "Lunar Touch", "damage": "0", "attacks": 0, "healing": 8, "mana_cost": 7, "weight": 3},
    {"name": "Thunderstorm", "damage": "2d6", "attacks": 2, "healing": 0, "mana_cost": 12, "weight": 2},
    {"name": "Raging Tempest", "damage": "1d8", "attacks": 4, "healing": 0, "mana_cost": 13, "weight": 2},
    {"name": "Void Touch", "damage": "2d4", "attacks": 1, "healing": 3, "mana_cost": 9, "weight": 3},
    {"name": "Hellfire Blast", "damage": "3d8", "attacks": 1, "healing": 0, "mana_cost": 14, "weight": 1},
    {"name": "Blood Boil", "damage": "1d6", "attacks": 3, "healing": 1, "mana_cost": 11, "weight": 2},
    {"name": "Crystal Edge", "damage": "2d6", "attacks": 2, "healing": 0, "mana_cost": 12, "weight": 2},
    {"name": "Echo Slam", "damage": "1d10", "attacks": 2, "healing": 0, "mana_cost": 11, "weight": 3},
    {"name": "Phantom Slice", "damage": "1d8", "attacks": 3, "healing": 0, "mana_cost": 12, "weight": 2},
    {"name": "Glacial Crush", "damage": "2d10", "attacks": 1, "healing": 0, "mana_cost": 14, "weight": 1},
    {"name": "Nature's Touch", "damage": "0", "attacks": 0, "healing": 5, "mana_cost": 4, "weight": 5},
    {"name": "Shadow Bite", "damage": "2d4", "attacks": 2, "healing": 0, "mana_cost": 8, "weight": 5},
    {"name": "Severing Light", "damage": "2d6", "attacks": 1, "healing": 0, "mana_cost": 10, "weight": 4},
    {"name": "Boulder Toss", "damage": "2d8", "attacks": 1, "healing": 0, "mana_cost": 12, "weight": 3},
    {"name": "Flame Wheel", "damage": "1d6", "attacks": 4, "healing": 0, "mana_cost": 11, "weight": 3},
    {"name": "Light of Hope", "damage": "0", "attacks": 0, "healing": 10, "mana_cost": 9, "weight": 2},
    {"name": "Crushing Blow", "damage": "3d6", "attacks": 1, "healing": 0, "mana_cost": 13, "weight": 2},
    {"name": "Toxic Spit", "damage": "1d8", "attacks": 2, "healing": 0, "mana_cost": 10, "weight": 3},
    {"name": "Ashen Grasp", "damage": "2d4", "attacks": 2, "healing": 0, "mana_cost": 9, "weight": 3},
    {"name": "Sacred Flame", "damage": "2d6", "attacks": 1, "healing": 2, "mana_cost": 11, "weight": 3},
    {"name": "Windslice", "damage": "1d4", "attacks": 5, "healing": 0, "mana_cost": 12, "weight": 2},
    {"name": "Stone Blast", "damage": "2d10", "attacks": 1, "healing": 0, "mana_cost": 15, "weight": 1},
    {"name": "Burning Lance", "damage": "2d8", "attacks": 1, "healing": 0, "mana_cost": 12, "weight": 2},
    {"name": "Ghoul Touch", "damage": "1d6", "attacks": 2, "healing": 3, "mana_cost": 11, "weight": 2},
    {"name": "Doom Ray", "damage": "4d6", "attacks": 1, "healing": 0, "mana_cost": 16, "weight": 1},
    {"name": "Starbolt", "damage": "3d4", "attacks": 2, "healing": 0, "mana_cost": 14, "weight": 2},
    {"name": "Aurora Veil", "damage": "0", "attacks": 0, "healing": 12, "mana_cost": 10, "weight": 1},
    {"name": "Arc Lightning", "damage": "1d6", "attacks": 5, "healing": 0, "mana_cost": 13, "weight": 1},
    {"name": "Final Judgment", "damage": "5d6", "attacks": 1, "healing": 0, "mana_cost": 18, "weight": 1},
    {"name": "Dragon’s Breath", "damage": "3d8", "attacks": 1, "healing": 0, "mana_cost": 17, "weight": 1},
    {"name": "Echoing Vow", "damage": "1d4", "attacks": 6, "healing": 0, "mana_cost": 13, "weight": 1},
    {"name": "Spectral Grasp", "damage": "1d8", "attacks": 2, "healing": 2, "mana_cost": 12, "weight": 1},
    {"name": "Phoenix Flame", "damage": "3d6", "attacks": 1, "healing": 4, "mana_cost": 16, "weight": 1},
    {"name": "Rune Implosion", "damage": "4d4", "attacks": 2, "healing": 0, "mana_cost": 15, "weight": 1},
    {"name": "Oblivion Ray", "damage": "6d6", "attacks": 1, "healing": 0, "mana_cost": 20, "weight": 1},
]

# === Monster List ===
monster_list = [
    {"name": "Slime", "health": 10, "damage": 2},
    {"name": "Goblin", "health": 13, "damage": 3},
    {"name": "Wolf", "health": 22, "damage": 4},
    {"name": "Glorbo", "health": 39, "damage": 5},
    {"name": "Hobblegobble", "health": 66, "damage": 6},
    {"name": "Furry", "health": 108, "damage": 8},
    {"name": "Bat", "health": 166, "damage": 12},
    {"name": "Zombie", "health": 243, "damage": 18},
    {"name": "Skeleton", "health": 342, "damage": 26},
    {"name": "Bandit", "health": 465, "damage": 35},
    {"name": "Ooze", "health": 616, "damage": 47},
    {"name": "Imp", "health": 797, "damage": 61},
    {"name": "Dire Rat", "health": 1010, "damage": 78},
    {"name": "Wasp", "health": 1260, "damage": 98},
    {"name": "Venom Slime", "health": 1547, "damage": 122},
    {"name": "Forest Spider", "health": 1876, "damage": 149},
    {"name": "Lurking Shade", "health": 2248, "damage": 180},
    {"name": "Thornbeast", "health": 2666, "damage": 216},
    {"name": "Cave Crab", "health": 3134, "damage": 255},
    {"name": "Blazing Lizard", "health": 3654, "damage": 300},
    {"name": "Fire Bat", "health": 4229, "damage": 349},
    {"name": "Ash Golem", "health": 4861, "damage": 404},
    {"name": "Feral Cat", "health": 5553, "damage": 465},
    {"name": "Bandit Archer", "health": 6307, "damage": 531},
    {"name": "Bog Wight", "health": 7128, "damage": 604},
    {"name": "Swamp Leech", "health": 8017, "damage": 683},
    {"name": "Ghostling", "health": 8977, "damage": 769},
    {"name": "Wraith", "health": 10010, "damage": 862},
    {"name": "Ghoul", "health": 11121, "damage": 963},
    {"name": "Frost Spider", "health": 12310, "damage": 1071},
    {"name": "Snow Wolf", "health": 13582, "damage": 1188},
    {"name": "Ice Elemental", "health": 14938, "damage": 1313},
    {"name": "Yeti Cub", "health": 16382, "damage": 1446},
    {"name": "Ice Bat", "health": 17916, "damage": 1589},
    {"name": "Rogue Mage", "health": 19543, "damage": 1740},
    {"name": "Stone Golem", "health": 21265, "damage": 1902},
    {"name": "Enchanted Armor", "health": 23086, "damage": 2073},
    {"name": "Cursed Knight", "health": 25008, "damage": 2254},
    {"name": "Dark Wolf", "health": 27034, "damage": 2446},
    {"name": "Bone Serpent", "health": 29167, "damage": 2649},
    {"name": "Fungal Beast", "health": 31409, "damage": 2864},
    {"name": "Scorpion", "health": 33763, "damage": 3089},
    {"name": "Flesh Golem", "health": 36232, "damage": 3327},
    {"name": "Thunder Lizard", "health": 38818, "damage": 3577},
    {"name": "Storm Bat", "health": 41525, "damage": 3839},
    {"name": "Lightning Elemental", "health": 44354, "damage": 4114},
    {"name": "Shadow Wyrm", "health": 47309, "damage": 4402},
    {"name": "Vampire Thrall", "health": 50393, "damage": 4704},
    {"name": "Specter", "health": 53608, "damage": 5020},
    {"name": "Crystal Spider", "health": 56957, "damage": 5349},
    {"name": "Iron Bear", "health": 60443, "damage": 5694},
    {"name": "Cave Troll", "health": 64068, "damage": 6053},
    {"name": "Bone Golem", "health": 67835, "damage": 6427},
    {"name": "Inferno Slime", "health": 71747, "damage": 6816},
    {"name": "Blood Hound", "health": 75807, "damage": 7222},
    {"name": "Hellbat", "health": 80017, "damage": 7644},
    {"name": "Nightmare", "health": 84380, "damage": 8082},
    {"name": "Dark Revenant", "health": 88899, "damage": 8537},
    {"name": "Arcane Construct", "health": 93577, "damage": 9009},
    {"name": "Twilight Stalker", "health": 98415, "damage": 9499},
    {"name": "Cursed Shade", "health": 103418, "damage": 10006},
    {"name": "Plague Rat", "health": 108588, "damage": 10532},
    {"name": "Toxic Crawler", "health": 113927, "damage": 11077},
    {"name": "Molten Fiend", "health": 119438, "damage": 11640},
    {"name": "Elder Wolf", "health": 125124, "damage": 12222},
    {"name": "Ancient Slime", "health": 130988, "damage": 12824},
    {"name": "Silver Knight", "health": 137032, "damage": 13446},
    {"name": "Giant Bat", "health": 143259, "damage": 14089},
    {"name": "Spectral Warrior", "health": 149673, "damage": 14752},
    {"name": "Lava Hound", "health": 156274, "damage": 15436},
    {"name": "Obsidian Golem", "health": 163068, "damage": 16141},
    {"name": "Corrupted Mage", "health": 170055, "damage": 16868},
    {"name": "Void Spawn", "health": 177239, "damage": 17617},
    {"name": "Ancient Shade", "health": 184623, "damage": 18388},
    {"name": "Phantom Beast", "health": 192209, "damage": 19182},
    {"name": "Dragon Whelp", "health": 200000, "damage": 20000},
]
